<?php
// $Id$

function child_nodes_nodeapi(&$node, $op, $teaser) {
  switch($op) {
    case 'view':
      if(!$teaser) {
        $sql = 'SELECT node.nid AS nid, ctp.field_photo_image_fid, ctp.field_photo_image_list,
              ctp.field_photo_image_data, node.type AS node_type, node.vid AS node_vid,
              node.title AS node_title
              FROM node LEFT JOIN content_type_photo ctp
              ON node.vid = ctp.vid
              WHERE ctp.field_photo_parent_place_nid = %d';
        
        $result = db_query($sql, $node->nid);
        while($row = db_fetch_object($result)) {
          $node->content['place_photos'] = array('#value'=> node_view(node_load($row->nid), true));
        }
        
      }
    break;
  }
}

function child_nodes_form_alter(&$form,&$form_state) {
  if(arg(1)=='add' && arg(2)=='photo') {
    $form['title'] = array(
      '#hidden' => TRUE,
    );
    return $form;
    
  }
}